steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'VITE_API_URL=${_VITE_API_URL}'
      - '-t'
      - 'gcr.io/$PROJECT_ID/frontend'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/frontend'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'intelgenz-app'
      - '--image'
      - 'gcr.io/$PROJECT_ID/frontend'
      - '--region'
      - 'asia-south1'
      - '--platform'
      - 'managed'

images:
  - 'gcr.io/$PROJECT_ID/frontend'

substitutions:
  _VITE_API_URL: 'https://intelgenz-uat-backend.onrender.com'
